INSERT INTO db_place_gsm_location (id, create_by, create_date, update_by, update_date, active_status, latitude, longitude, aptitude) VALUES (1, 1, '2020-04-17', null, null, true, 33, 32, 43);
INSERT INTO db_place_gsm_location (id, create_by, create_date, update_by, update_date, active_status, latitude, longitude, aptitude) VALUES (2, 1, '2020-04-17', null, null, true, 87, 65, null);

INSERT INTO db_place_thana (id, create_by, create_date, update_by, update_date, active_status, name, district_id) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ', 41);
INSERT INTO db_place_thana (id, create_by, create_date, update_by, update_date, active_status, name, district_id) VALUES (2, 1, '2020-04-17', null, null, true, 'ঢাকা', 18);

INSERT INTO db_place_place (id, create_by, create_date, update_by, update_date, active_status, name, thana_id, gsm_location_id) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ বাজার', 1, 1);
INSERT INTO db_place_place (id, create_by, create_date, update_by, update_date, active_status, name, thana_id, gsm_location_id) VALUES (2, 1, '2020-04-17', null, null, true, 'ঢাকা গুলিস্তান', 2, 2);
INSERT INTO db_ficket_ride_config (id, create_by, create_date, update_by, update_date, active_status, name, description, start_time, from_place_id, reach_time, to_place_id, time_factor) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ থেকে ঢাকা', 'গেইটলক সার্ভিস', '10:00:00', 1, '06:00:00', 2, '00:30:00');
INSERT INTO db_ficket_car_config (id, create_by, create_date, update_by, update_date, active_status, ticket_price, total_seat, seat_config_id) VALUES (1, 1, '2020-04-17', null, null, true, 500.00, 55, 1);
INSERT INTO jt_db_ficket_car_config_x_db_ficket_ride_config (car_config_id, ride_config_id) VALUES (1, 1);
INSERT INTO db_ficket_agency_info (id, create_by, create_date, update_by, update_date, active_status, head_quarter_id) VALUES (1, 1, '2020-04-17', null, null, true, 1);
INSERT INTO db_ficket_travel_agency (id, create_by, create_date, update_by, update_date, active_status, agency_name, agency_info_id) VALUES (1, 1, '2020-04-17', null, null, true, 'প্রিয় এক্সপ্রেস', 1);
INSERT INTO db_ficket_car (id, create_by, create_date, update_by, update_date, active_status, name, licence, number_plate, car_type, travel_agency_id, car_config_id) VALUES (1, 1, '2020-04-17', null, null, true, 'প্রিয় এক্সপ্রেস ০৮', 'এনডি৩৩২৩২২', 'খ-৪৫৬৬৫৪', 'BUS', 1, 1);


UPDATE public.db_place_district SET name = 'বরগুনা' WHERE id = 1;
UPDATE public.db_place_district SET name = 'বরিশাল' WHERE id = 2;
UPDATE public.db_place_district SET name = 'ভোলা' WHERE id = 3;
UPDATE public.db_place_district SET name = 'ঝালকাঠী' WHERE id = 4;
UPDATE public.db_place_district SET name = 'পটুয়াখালী' WHERE id = 5;
UPDATE public.db_place_district SET name = 'পিরোজপুর' WHERE id = 6;
UPDATE public.db_place_district SET name = 'বান্দরবান' WHERE id = 7;
UPDATE public.db_place_district SET name = 'ব্রাহ্মণবাড়িয়া' WHERE id = 8;
UPDATE public.db_place_district SET name = 'চাঁদপুর' WHERE id = 9;
UPDATE public.db_place_district SET name = 'চট্টগ্রাম' WHERE id = 10;
UPDATE public.db_place_district SET name = 'কক্সবাজার' WHERE id = 11;
UPDATE public.db_place_district SET name = 'কুমিল্লা' WHERE id = 12;
UPDATE public.db_place_district SET name = 'ফেনী' WHERE id = 13;
UPDATE public.db_place_district SET name = 'খাগড়াছড়ি' WHERE id = 14;
UPDATE public.db_place_district SET name = 'লক্ষ্মীপুর' WHERE id = 15;
UPDATE public.db_place_district SET name = 'নোয়াখালী' WHERE id = 16;
UPDATE public.db_place_district SET name = 'রাঙামাটি' WHERE id = 17;
UPDATE public.db_place_district SET name = 'ঢাকা' WHERE id = 18;
UPDATE public.db_place_district SET name = 'ফরিদপুর' WHERE id = 19;
UPDATE public.db_place_district SET name = 'গাজীপুর' WHERE id = 20;
UPDATE public.db_place_district SET name = 'গোপালগঞ্জ' WHERE id = 21;
UPDATE public.db_place_district SET name = 'কিশোরগঞ্জ' WHERE id = 22;
UPDATE public.db_place_district SET name = 'মাদারীপুর' WHERE id = 23;
UPDATE public.db_place_district SET name = 'মানিকগঞ্জ' WHERE id = 24;
UPDATE public.db_place_district SET name = 'মুন্সীগঞ্জ' WHERE id = 25;
UPDATE public.db_place_district SET name = 'নারায়ণগঞ্জ' WHERE id = 26;
UPDATE public.db_place_district SET name = 'নরসিংদী' WHERE id = 27;
UPDATE public.db_place_district SET name = 'রাজবাড়ী' WHERE id = 28;
UPDATE public.db_place_district SET name = 'শরীয়তপুর' WHERE id = 29;
UPDATE public.db_place_district SET name = 'টাঙ্গাইল' WHERE id = 30;
UPDATE public.db_place_district SET name = 'বাগেরহাট' WHERE id = 31;
UPDATE public.db_place_district SET name = 'চুয়াডাঙ্গা' WHERE id = 32;
UPDATE public.db_place_district SET name = 'যশোর' WHERE id = 33;
UPDATE public.db_place_district SET name = 'ঝিনাইদাহ' WHERE id = 34;
UPDATE public.db_place_district SET name = 'খুলনা' WHERE id = 35;
UPDATE public.db_place_district SET name = 'কুষ্টিয়া' WHERE id = 36;
UPDATE public.db_place_district SET name = 'মাগুরা' WHERE id = 37;
UPDATE public.db_place_district SET name = 'মেহেরপুর' WHERE id = 38;
UPDATE public.db_place_district SET name = 'নড়াইল' WHERE id = 39;
UPDATE public.db_place_district SET name = 'সাতক্ষীরা' WHERE id = 40;
UPDATE public.db_place_district SET name = 'জামালপুর' WHERE id = 41;
UPDATE public.db_place_district SET name = 'ময়মনসিংহ' WHERE id = 42;
UPDATE public.db_place_district SET name = 'নেত্রকোনা' WHERE id = 43;
UPDATE public.db_place_district SET name = 'শেরপুর' WHERE id = 44;
UPDATE public.db_place_district SET name = 'বগুড়া' WHERE id = 45;
UPDATE public.db_place_district SET name = 'জয়পুরহাট' WHERE id = 46;
UPDATE public.db_place_district SET name = 'নওগাঁ' WHERE id = 47;
UPDATE public.db_place_district SET name = 'নাটোর' WHERE id = 48;
UPDATE public.db_place_district SET name = 'চাঁপাইনবাবগঞ্জ' WHERE id = 49;
UPDATE public.db_place_district SET name = 'পাবনা' WHERE id = 50;
UPDATE public.db_place_district SET name = 'রাজশাহী' WHERE id = 51;
UPDATE public.db_place_district SET name = 'সিরাজগঞ্জ' WHERE id = 52;
UPDATE public.db_place_district SET name = 'দিনাজপুর' WHERE id = 53;
UPDATE public.db_place_district SET name = 'গাইবন্ধা' WHERE id = 54;
UPDATE public.db_place_district SET name = 'কুড়িগ্রাম' WHERE id = 55;
UPDATE public.db_place_district SET name = 'লালমনিরহাট' WHERE id = 56;
UPDATE public.db_place_district SET name = 'নীলফামারী' WHERE id = 57;
UPDATE public.db_place_district SET name = 'পঞ্চগড়' WHERE id = 58;
UPDATE public.db_place_district SET name = 'রংপুর' WHERE id = 59;
UPDATE public.db_place_district SET name = 'ঠাকুরগাঁও' WHERE id = 60;
UPDATE public.db_place_district SET name = 'হবিগঞ্জ' WHERE id = 61;
UPDATE public.db_place_district SET name = 'মৌলভীবাজার' WHERE id = 62;
UPDATE public.db_place_district SET name = 'সুনামগঞ্জ' WHERE id = 63;
UPDATE public.db_place_district SET name = 'সিলেট' WHERE id = 64;
