INSERT INTO db_place_gsm_location (id, create_by, create_date, update_by, update_date, active_status, latitude, longitude, aptitude) VALUES (1, 1, '2020-04-17', null, null, true, 33, 32, 43);
INSERT INTO db_place_gsm_location (id, create_by, create_date, update_by, update_date, active_status, latitude, longitude, aptitude) VALUES (2, 1, '2020-04-17', null, null, true, 87, 65, null);

INSERT INTO db_place_thana (id, create_by, create_date, update_by, update_date, active_status, name, district_id) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ', 41);
INSERT INTO db_place_thana (id, create_by, create_date, update_by, update_date, active_status, name, district_id) VALUES (2, 1, '2020-04-17', null, null, true, 'ঢাকা', 18);

INSERT INTO db_place_place (id, create_by, create_date, update_by, update_date, active_status, name, thana_id, gsm_location_id) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ বাজার', 1, 1);
INSERT INTO db_place_place (id, create_by, create_date, update_by, update_date, active_status, name, thana_id, gsm_location_id) VALUES (2, 1, '2020-04-17', null, null, true, 'ঢাকা গুলিস্তান', 2, 2);
INSERT INTO db_ficket_ride_config (id, create_by, create_date, update_by, update_date, active_status, name, description, start_time, from_place_id, reach_time, to_place_id, time_factor) VALUES (1, 1, '2020-04-17', null, null, true, 'বকশীগঞ্জ থেকে ঢাকা', 'গেইটলক সার্ভিস', '10:00:00', 1, '06:00:00', 2, '00:30:00');
INSERT INTO db_ficket_car_config (id, create_by, create_date, update_by, update_date, active_status, ticket_price, total_seat, seat_config_id) VALUES (1, 1, '2020-04-17', null, null, true, 500.00, 55, 1);
INSERT INTO jt_db_ficket_car_config_x_db_ficket_ride_config (car_config_id, ride_config_id) VALUES (1, 1);
INSERT INTO db_ficket_agency_info (id, create_by, create_date, update_by, update_date, active_status, head_quarter_id) VALUES (1, 1, '2020-04-17', null, null, true, 1);
INSERT INTO db_ficket_travel_agency (id, create_by, create_date, update_by, update_date, active_status, agency_name, agency_info_id) VALUES (1, 1, '2020-04-17', null, null, true, 'প্রিয় এক্সপ্রেস', 1);
INSERT INTO db_ficket_car (id, create_by, create_date, update_by, update_date, active_status, name, licence, number_plate, car_type, travel_agency_id, car_config_id) VALUES (1, 1, '2020-04-17', null, null, true, 'প্রিয় এক্সপ্রেস ০৮', 'এনডি৩৩২৩২২', 'খ-৪৫৬৬৫৪', 'BUS', 1, 1);


UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'বরগুনা', division_id = 1 WHERE id = 1;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'বরিশাল', division_id = 1 WHERE id = 2;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ভোলা', division_id = 1 WHERE id = 3;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ঝালকাঠী', division_id = 1 WHERE id = 4;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'পটুয়াখালী', division_id = 1 WHERE id = 5;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'পিরোজপুর', division_id = 1 WHERE id = 6;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'বান্দরবান', division_id = 2 WHERE id = 7;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ব্রাহ্মণবাড়িয়া', division_id = 2 WHERE id = 8;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'চাঁদপুর', division_id = 2 WHERE id = 9;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'চট্টগ্রাম', division_id = 2 WHERE id = 10;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'কক্সবাজার', division_id = 2 WHERE id = 11;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'কুমিল্লা', division_id = 2 WHERE id = 12;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ফেনী', division_id = 2 WHERE id = 13;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'খাগড়াছড়ি', division_id = 2 WHERE id = 14;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'লক্ষ্মীপুর', division_id = 2 WHERE id = 15;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নোয়াখালী', division_id = 2 WHERE id = 16;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'রাঙামাটি', division_id = 2 WHERE id = 17;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ঢাকা', division_id = 3 WHERE id = 18;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ফরিদপুর', division_id = 3 WHERE id = 19;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'গাজীপুর', division_id = 3 WHERE id = 20;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'গোপালগঞ্জ', division_id = 3 WHERE id = 21;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'কিশোরগঞ্জ', division_id = 3 WHERE id = 22;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মাদারীপুর', division_id = 3 WHERE id = 23;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মানিকগঞ্জ', division_id = 3 WHERE id = 24;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মুন্সীগঞ্জ', division_id = 3 WHERE id = 25;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নারায়ণগঞ্জ', division_id = 3 WHERE id = 26;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নরসিংদী', division_id = 3 WHERE id = 27;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'রাজবাড়ী', division_id = 3 WHERE id = 28;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'শরীয়তপুর', division_id = 3 WHERE id = 29;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'টাঙ্গাইল', division_id = 3 WHERE id = 30;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'বাগেরহাট', division_id = 4 WHERE id = 31;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'চুয়াডাঙ্গা', division_id = 4 WHERE id = 32;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'যশোর', division_id = 4 WHERE id = 33;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ঝিনাইদাহ', division_id = 4 WHERE id = 34;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'খুলনা', division_id = 4 WHERE id = 35;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'কুষ্টিয়া', division_id = 4 WHERE id = 36;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মাগুরা', division_id = 4 WHERE id = 37;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মেহেরপুর', division_id = 4 WHERE id = 38;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নড়াইল', division_id = 4 WHERE id = 39;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'সাতক্ষীরা', division_id = 4 WHERE id = 40;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'জামালপুর', division_id = 5 WHERE id = 41;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ময়মনসিংহ', division_id = 5 WHERE id = 42;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নেত্রকোনা', division_id = 5 WHERE id = 43;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'শেরপুর', division_id = 5 WHERE id = 44;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'বগুড়া', division_id = 6 WHERE id = 45;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'জয়পুরহাট', division_id = 6 WHERE id = 46;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নওগাঁ', division_id = 6 WHERE id = 47;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নাটোর', division_id = 6 WHERE id = 48;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'চাঁপাইনবাবগঞ্জ', division_id = 6 WHERE id = 49;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'পাবনা', division_id = 6 WHERE id = 50;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'রাজশাহী', division_id = 6 WHERE id = 51;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'সিরাজগঞ্জ', division_id = 6 WHERE id = 52;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'দিনাজপুর', division_id = 7 WHERE id = 53;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'গাইবন্ধা', division_id = 7 WHERE id = 54;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'কুড়িগ্রাম', division_id = 7 WHERE id = 55;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'লালমনিরহাট', division_id = 7 WHERE id = 56;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'নীলফামারী', division_id = 7 WHERE id = 57;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'পঞ্চগড়', division_id = 7 WHERE id = 58;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'রংপুর', division_id = 7 WHERE id = 59;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'ঠাকুরগাঁও', division_id = 7 WHERE id = 60;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'হবিগঞ্জ', division_id = 8 WHERE id = 61;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'মৌলভীবাজার', division_id = 8 WHERE id = 62;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'সুনামগঞ্জ', division_id = 8 WHERE id = 63;
UPDATE public.db_place_district SET create_by = 1, create_date = '2020-05-16', update_by = null, update_date = null, active_status = true, name = 'সিলেট', division_id = 8 WHERE id = 64;
